[project]
name = "numcompute_stream"
version = "1.0.1"
dependencies = ["numpy"]
requires-python = ">=3.13"
description = "Assignment 2.2 streaming, decision tree–based machine learning framework"
readme = "README.md"

[project.urls]
Repository = "https://github.com/davetrumbull/comp_5004_ass2-1_numpy_newbies.git"
Issues = "https://github.com/davetrumbull/comp_5004_ass2-1_numpy_newbies/issues"

[project.optional-dependencies]

dev = [
    "pytest",
    "flake8",
    "pytest-cov",
    "matplotlib",
    "microbench",
    "pandas"
]
test = [
    "pytest",
    "pytest-cov"
]

[tool.setuptools.packages.find]
include = ["numcompute_stream*"]

[tool.coverage.report]
exclude_also = [
    "@(abc\\.)?abstractmethod",
]